//
//  MockLibraryData.swift
//  Twyst
//
//  Created by Karo on 05.10.2025.
//

import Foundation

struct MockLibraryData {
    // MARK: - Users Data (100 users)
    static let allUsers: [(String, String, Int)] = [
        ("Emily Johnson", "emilyjohnson", 234),
        ("Michael Chen", "mikechen", 189),
        ("Sarah Williams", "sarahfit", 456),
        ("David Brown", "davidb", 123),
        ("Jessica Martinez", "jessicam", 567),
        ("James Taylor", "jamest", 321),
        ("Ashley Anderson", "ashleya", 445),
        ("Christopher Lee", "chrislee", 278),
        ("Amanda White", "amandaw", 392),
        ("Matthew Harris", "matthewh", 156),
        ("Jennifer Clark", "jenniferc", 489),
        ("Daniel Lewis", "daniell", 234),
        ("Lisa Robinson", "lisar", 367),
        ("Andrew Walker", "andreww", 298),
        ("Karen Hall", "karenh", 412),
        ("Kevin Young", "keviny", 178),
        ("Nancy Allen", "nancya", 523),
        ("Brian King", "briank", 267),
        ("Betty Wright", "bettyw", 334),
        ("George Scott", "georges", 445),
        ("Sandra Green", "sandrag", 289),
        ("Kenneth Adams", "kennetha", 356),
        ("Donna Baker", "donnab", 478),
        ("Steven Nelson", "stevenn", 201),
        ("Carol Carter", "carolc", 389),
        ("Edward Mitchell", "edwardm", 267),
        ("Michelle Perez", "michellep", 512),
        ("Jason Roberts", "jasonr", 234),
        ("Laura Turner", "laurat", 445),
        ("Thomas Phillips", "thomasp", 178),
        ("Helen Campbell", "helenc", 356),
        ("Jeffrey Parker", "jeffreyp", 289),
        ("Deborah Evans", "deborahe", 423),
        ("Ryan Edwards", "ryane", 267),
        ("Sharon Collins", "sharonc", 389),
        ("Gary Stewart", "garys", 234),
        ("Cynthia Sanchez", "cynthias", 467),
        ("Nicholas Morris", "nicholasm", 198),
        ("Kathleen Rogers", "kathleenr", 378),
        ("Eric Reed", "ericr", 245),
        ("Angela Cook", "angelac", 456),
        ("Jacob Morgan", "jacobm", 312),
        ("Shirley Bell", "shirleyb", 389),
        ("Jonathan Murphy", "jonathanm", 223),
        ("Brenda Bailey", "brendab", 434),
        ("Brandon Rivera", "brandonr", 278),
        ("Amy Cooper", "amyc", 367),
        ("Justin Richardson", "justinr", 189),
        ("Kimberly Cox", "kimberlys", 445),
        ("Tyler Howard", "tylerh", 234),
        ("Melissa Ward", "melissaw", 389),
        ("Aaron Torres", "aaront", 267),
        ("Dorothy Peterson", "dorothyp", 312),
        ("Jose Gray", "joseg", 445),
        ("Christina Ramirez", "christinar", 234),
        ("Adam James", "adamj", 378),
        ("Stephanie Watson", "stephaniew", 289),
        ("Zachary Brooks", "zacharyb", 423),
        ("Virginia Kelly", "virginiak", 356),
        ("Henry Sanders", "henrys", 267),
        ("Rachel Price", "rachelp", 489),
        ("Nathan Bennett", "nathanb", 198),
        ("Carolyn Wood", "carolynw", 367),
        ("Douglas Barnes", "douglasb", 234),
        ("Janet Ross", "janetr", 445),
        ("Peter Henderson", "peterh", 289),
        ("Catherine Coleman", "catherinec", 378),
        ("Kyle Jenkins", "kylej", 312),
        ("Maria Perry", "mariap", 456),
        ("Noah Powell", "noahp", 234),
        ("Heather Long", "heatherl", 389),
        ("Ethan Patterson", "ethanp", 267),
        ("Diane Hughes", "dianeh", 423),
        ("Jeremy Flores", "jeremyf", 198),
        ("Julie Washington", "juliew", 367),
        ("Walter Butler", "walterb", 289),
        ("Joyce Simmons", "joyces", 445),
        ("Christian Foster", "christianf", 234),
        ("Evelyn Gonzales", "evelyng", 378),
        ("Austin Bryant", "austinb", 312),
        ("Frances Alexander", "francesa", 456),
        ("Benjamin Russell", "benjaminr", 223),
        ("Cheryl Griffin", "cherylg", 389),
        ("Samuel Diaz", "samueld", 267),
        ("Marie Hayes", "marieh", 434),
        ("Logan Myers", "loganm", 189),
        ("Denise Ford", "denisef", 367),
        ("Jack Hamilton", "jackh", 245),
        ("Pamela Graham", "pamelag", 423),
        ("Albert Sullivan", "alberts", 312),
        ("Teresa Wallace", "teresaw", 378),
        ("Jordan Woods", "jordanw", 234),
        ("Doris Cole", "dorisc", 456),
        ("Gabriel West", "gabrielw", 289),
        ("Judith Jordan", "judithj", 389),
        ("Alexander Owens", "alexandero", 267),
        ("Emma Reynolds", "emmar", 445),
        ("Isaac Fisher", "isaacf", 198),
        ("Olivia Ellis", "oliviae", 523)
    ]
    
    // MARK: - Exercises Data (100 exercises)
    static let allExercises: [(String, String, String, String)] = [
        ("Push-ups", "10 min", "Beginner", "Strength"),
        ("Plank Hold", "5 min", "Intermediate", "Strength"),
        ("Jump Rope", "15 min", "Beginner", "Cardio"),
        ("Advanced Squats", "20 min", "Advanced", "Strength"),
        ("HIIT Workout", "30 min", "Advanced", "Cardio"),
        ("Yoga Flow", "25 min", "Intermediate", "Flexibility"),
        ("Morning Stretch", "10 min", "Beginner", "Flexibility"),
        ("Core Workout", "15 min", "Intermediate", "Strength"),
        ("Lunges", "12 min", "Beginner", "Strength"),
        ("Side Plank", "8 min", "Intermediate", "Balance"),
        ("Running", "20 min", "Beginner", "Cardio"),
        ("Bicycle Crunches", "10 min", "Intermediate", "Strength"),
        ("Deadlift Form", "18 min", "Advanced", "Strength"),
        ("Power Yoga", "22 min", "Advanced", "Flexibility"),
        ("Sprint Training", "15 min", "Advanced", "Cardio"),
        ("Evening Yoga", "20 min", "Beginner", "Flexibility"),
        ("Quick Cardio", "10 min", "Beginner", "Cardio"),
        ("Pull-ups", "12 min", "Advanced", "Strength"),
        ("Mountain Climbers", "8 min", "Intermediate", "Cardio"),
        ("Leg Raises", "10 min", "Beginner", "Strength"),
        ("Burpees", "15 min", "Advanced", "Cardio"),
        ("Wall Sits", "5 min", "Beginner", "Strength"),
        ("Box Jumps", "12 min", "Advanced", "Cardio"),
        ("Chest Press", "15 min", "Intermediate", "Strength"),
        ("Swimming", "30 min", "Beginner", "Cardio"),
        ("Pilates Core", "20 min", "Intermediate", "Flexibility"),
        ("Battle Ropes", "10 min", "Advanced", "Cardio"),
        ("Shoulder Press", "12 min", "Intermediate", "Strength"),
        ("Kettlebell Swings", "15 min", "Advanced", "Strength"),
        ("Tai Chi", "25 min", "Beginner", "Balance"),
        ("Turkish Get-ups", "18 min", "Advanced", "Strength"),
        ("Rowing Machine", "20 min", "Intermediate", "Cardio"),
        ("Hip Bridges", "8 min", "Beginner", "Strength"),
        ("Medicine Ball Slams", "10 min", "Advanced", "Cardio"),
        ("Foam Rolling", "15 min", "Beginner", "Flexibility"),
        ("Bear Crawls", "12 min", "Intermediate", "Cardio"),
        ("Single-Leg Balance", "10 min", "Beginner", "Balance"),
        ("Clean and Press", "18 min", "Advanced", "Strength"),
        ("Stair Climbing", "20 min", "Intermediate", "Cardio"),
        ("Calf Raises", "8 min", "Beginner", "Strength"),
        ("Farmer's Walk", "12 min", "Intermediate", "Strength"),
        ("Handstand Practice", "15 min", "Advanced", "Balance"),
        ("Jumping Jacks", "10 min", "Beginner", "Cardio"),
        ("Russian Twists", "8 min", "Intermediate", "Strength"),
        ("Back Extensions", "10 min", "Beginner", "Strength"),
        ("Plyometric Jumps", "15 min", "Advanced", "Cardio"),
        ("Dynamic Stretching", "12 min", "Beginner", "Flexibility"),
        ("Arnold Press", "15 min", "Advanced", "Strength"),
        ("Cycling", "30 min", "Intermediate", "Cardio"),
        ("Tricep Dips", "10 min", "Intermediate", "Strength"),
        ("Weighted Squats", "18 min", "Advanced", "Strength"),
        ("Elliptical", "25 min", "Beginner", "Cardio"),
        ("Resistance Band Workout", "20 min", "Beginner", "Strength"),
        ("Agility Ladder", "12 min", "Intermediate", "Cardio"),
        ("Superman Exercise", "8 min", "Beginner", "Strength"),
        ("Thrusters", "15 min", "Advanced", "Strength"),
        ("Dance Cardio", "20 min", "Intermediate", "Cardio"),
        ("Quad Stretches", "10 min", "Beginner", "Flexibility"),
        ("Bench Press", "18 min", "Advanced", "Strength"),
        ("Shadowboxing", "15 min", "Intermediate", "Cardio"),
        ("Glute Bridges", "10 min", "Beginner", "Strength"),
        ("Snatch Practice", "20 min", "Advanced", "Strength"),
        ("Step-ups", "12 min", "Intermediate", "Cardio"),
        ("Hamstring Curls", "10 min", "Beginner", "Strength"),
        ("Rope Climbing", "15 min", "Advanced", "Strength"),
        ("Kickboxing", "25 min", "Advanced", "Cardio"),
        ("Cat-Cow Stretch", "8 min", "Beginner", "Flexibility"),
        ("Front Squats", "18 min", "Advanced", "Strength"),
        ("Incline Walking", "20 min", "Beginner", "Cardio"),
        ("Lateral Raises", "10 min", "Intermediate", "Strength"),
        ("Pistol Squats", "15 min", "Advanced", "Balance"),
        ("Zumba", "30 min", "Intermediate", "Cardio"),
        ("Chin-ups", "12 min", "Advanced", "Strength"),
        ("Ankle Circles", "5 min", "Beginner", "Balance"),
        ("Overhead Squats", "18 min", "Advanced", "Strength"),
        ("Jump Squats", "10 min", "Intermediate", "Cardio"),
        ("Child's Pose Hold", "8 min", "Beginner", "Flexibility"),
        ("Muscle-ups", "15 min", "Advanced", "Strength"),
        ("Shadow Running", "12 min", "Intermediate", "Cardio"),
        ("Wrist Rolls", "5 min", "Beginner", "Flexibility"),
        ("Dragon Flags", "10 min", "Advanced", "Strength"),
        ("Treadmill Intervals", "20 min", "Advanced", "Cardio"),
        ("Neck Stretches", "8 min", "Beginner", "Flexibility"),
        ("Weighted Lunges", "15 min", "Intermediate", "Strength"),
        ("Spin Class", "30 min", "Advanced", "Cardio"),
        ("Hip Flexor Stretch", "10 min", "Beginner", "Flexibility"),
        ("Barbell Rows", "15 min", "Advanced", "Strength"),
        ("Mountain Running", "25 min", "Advanced", "Cardio"),
        ("IT Band Stretch", "8 min", "Beginner", "Flexibility"),
        ("Dumbbell Flyes", "12 min", "Intermediate", "Strength"),
        ("Beach Volleyball", "30 min", "Intermediate", "Cardio"),
        ("Pigeon Pose", "10 min", "Beginner", "Flexibility"),
        ("Power Cleans", "18 min", "Advanced", "Strength"),
        ("Basketball Drills", "25 min", "Intermediate", "Cardio"),
        ("Butterfly Stretch", "8 min", "Beginner", "Flexibility"),
        ("Weighted Dips", "15 min", "Advanced", "Strength"),
        ("Tennis Practice", "30 min", "Intermediate", "Cardio"),
        ("Spinal Twists", "10 min", "Beginner", "Flexibility")
    ]
    
    // MARK: - Exercise Packs Data (100 packs)
    static let allPacks: [(String, Int, String, String)] = [
        ("Beginner's Bundle", 12, "pack", "Beginner"),
        ("Strength Master Pack", 20, "pack", "Advanced"),
        ("Flexibility Fundamentals", 15, "pack", "Intermediate"),
        ("Quick Start Pack", 8, "pack", "Beginner"),
        ("Total Body Transform", 25, "pack", "Advanced"),
        ("Morning Energy Pack", 10, "pack", "Beginner"),
        ("Athlete's Edge", 30, "pack", "Advanced"),
        ("Yoga Essentials", 18, "pack", "Intermediate"),
        ("Fat Burning Bundle", 22, "pack", "Advanced"),
        ("Balance & Core", 14, "pack", "Intermediate"),
        ("Home Workout Pack", 16, "pack", "Beginner"),
        ("Power Builder", 28, "pack", "Advanced"),
        ("Stretch & Flex", 12, "pack", "Beginner"),
        ("HIIT Master Bundle", 24, "pack", "Advanced"),
        ("Gentle Flow Pack", 10, "pack", "Beginner"),
        ("CrossFit Essentials", 32, "pack", "Advanced"),
        ("Recovery & Mobility", 14, "pack", "Intermediate"),
        ("Beach Body Bundle", 20, "pack", "Intermediate"),
        ("Strength Foundation", 16, "pack", "Beginner"),
        ("Elite Performance", 35, "pack", "Advanced"),
        ("Daily Stretch Pack", 8, "pack", "Beginner"),
        ("Muscle Building Bundle", 26, "pack", "Advanced"),
        ("Cardio Blast Pack", 18, "pack", "Intermediate"),
        ("Weekend Warrior", 12, "pack", "Intermediate"),
        ("Ultimate Fitness", 40, "pack", "Advanced"),
        ("Senior Fitness Pack", 10, "pack", "Beginner"),
        ("Bodyweight Mastery", 22, "pack", "Advanced"),
        ("Pilates Complete", 16, "pack", "Intermediate"),
        ("Quick Burn Bundle", 14, "pack", "Intermediate"),
        ("Functional Strength", 24, "pack", "Advanced"),
        ("Flexibility Plus", 12, "pack", "Beginner"),
        ("Kettlebell Collection", 20, "pack", "Advanced"),
        ("Office Worker Pack", 10, "pack", "Beginner"),
        ("Athletic Performance", 28, "pack", "Advanced"),
        ("Prenatal Fitness", 14, "pack", "Beginner"),
        ("Olympic Lifting", 30, "pack", "Advanced"),
        ("Balance Training", 12, "pack", "Intermediate"),
        ("Marathon Prep Pack", 32, "pack", "Advanced"),
        ("Desk Stretches", 8, "pack", "Beginner"),
        ("PowerLifting Bundle", 26, "pack", "Advanced"),
        ("Dance Fitness Pack", 18, "pack", "Intermediate"),
        ("Combat Training", 24, "pack", "Advanced"),
        ("Meditation & Stretch", 10, "pack", "Beginner"),
        ("Explosive Power", 28, "pack", "Advanced"),
        ("Joint Health Pack", 12, "pack", "Beginner"),
        ("Strongman Training", 30, "pack", "Advanced"),
        ("Barre Workout Bundle", 16, "pack", "Intermediate"),
        ("Speed & Agility", 20, "pack", "Advanced"),
        ("Posture Correction", 10, "pack", "Beginner"),
        ("Bodybuilding Basics", 32, "pack", "Advanced"),
        ("Low Impact Cardio", 14, "pack", "Beginner"),
        ("Calisthenics Master", 26, "pack", "Advanced"),
        ("Stretching Routine", 12, "pack", "Beginner"),
        ("MMA Conditioning", 28, "pack", "Advanced"),
        ("Chair Exercises", 10, "pack", "Beginner"),
        ("Gymnastic Strength", 34, "pack", "Advanced"),
        ("Foam Rolling Guide", 8, "pack", "Beginner"),
        ("Rock Climbing Prep", 22, "pack", "Advanced"),
        ("Walking Workouts", 12, "pack", "Beginner"),
        ("Triathlon Training", 36, "pack", "Advanced"),
        ("Breathing Exercises", 6, "pack", "Beginner"),
        ("Advanced Plyometrics", 24, "pack", "Advanced"),
        ("Gentle Yoga Pack", 14, "pack", "Beginner"),
        ("Ninja Warrior Training", 30, "pack", "Advanced"),
        ("Mobility Drills", 16, "pack", "Intermediate"),
        ("Swimming Techniques", 18, "pack", "Intermediate"),
        ("Resistance Band Bundle", 12, "pack", "Beginner"),
        ("Boxing Fundamentals", 20, "pack", "Advanced"),
        ("Active Aging Pack", 10, "pack", "Beginner"),
        ("Parkour Basics", 22, "pack", "Advanced"),
        ("Stress Relief Stretches", 8, "pack", "Beginner"),
        ("Weightlifting Programs", 28, "pack", "Advanced"),
        ("Cardio for Beginners", 14, "pack", "Beginner"),
        ("Sports Conditioning", 26, "pack", "Advanced"),
        ("Morning Yoga Flow", 12, "pack", "Beginner"),
        ("Tactical Fitness", 32, "pack", "Advanced"),
        ("Evening Wind-Down", 10, "pack", "Beginner"),
        ("Military Training", 34, "pack", "Advanced"),
        ("Kids Fitness Fun", 8, "pack", "Beginner"),
        ("Spartan Race Prep", 30, "pack", "Advanced"),
        ("Pregnancy Yoga", 14, "pack", "Beginner"),
        ("Iron Man Training", 40, "pack", "Advanced"),
        ("Couples Workout", 16, "pack", "Intermediate"),
        ("Navy SEAL Fitness", 36, "pack", "Advanced"),
        ("Family Activities", 12, "pack", "Beginner"),
        ("Obstacle Course Prep", 28, "pack", "Advanced"),
        ("Arthritis-Friendly", 10, "pack", "Beginner"),
        ("Extreme Conditioning", 32, "pack", "Advanced"),
        ("Mindful Movement", 12, "pack", "Beginner"),
        ("Special Ops Training", 38, "pack", "Advanced"),
        ("Beginner Stretches", 8, "pack", "Beginner"),
        ("Ultimate Warrior", 42, "pack", "Advanced"),
        ("Balance for Seniors", 10, "pack", "Beginner"),
        ("Pro Athlete Bundle", 45, "pack", "Advanced"),
        ("Couch to Active", 12, "pack", "Beginner"),
        ("Beast Mode Pack", 40, "pack", "Advanced"),
        ("Gentle Cardio", 10, "pack", "Beginner"),
        ("Elite Training System", 50, "pack", "Advanced")
    ]
    
    // MARK: - Challenges Data (100 challenges)
    static let allChallenges: [(String, Int, String, String)] = [
        ("30-Day Transformation", 30, "challenge", "Intermediate"),
        ("Advanced Athlete", 45, "challenge", "Advanced"),
        ("Beginner's Journey", 14, "challenge", "Beginner"),
        ("Core Strength Challenge", 21, "challenge", "Intermediate"),
        ("100 Push-ups Challenge", 30, "challenge", "Advanced"),
        ("Flexibility Quest", 28, "challenge", "Beginner"),
        ("Iron Body Challenge", 60, "challenge", "Advanced"),
        ("Morning Routine Challenge", 21, "challenge", "Beginner"),
        ("Beast Mode 90", 90, "challenge", "Advanced"),
        ("Yoga Every Day", 30, "challenge", "Intermediate"),
        ("Plank Master", 30, "challenge", "Intermediate"),
        ("Run 5K Challenge", 42, "challenge", "Beginner"),
        ("Muscle Gain Mission", 60, "challenge", "Advanced"),
        ("Stretch Daily", 30, "challenge", "Beginner"),
        ("Cardio Warrior", 45, "challenge", "Advanced"),
        ("Balance Quest", 21, "challenge", "Intermediate"),
        ("Weight Loss Journey", 90, "challenge", "Intermediate"),
        ("Beginner's First Step", 7, "challenge", "Beginner"),
        ("Spartan Challenge", 60, "challenge", "Advanced"),
        ("Flexibility Master", 45, "challenge", "Intermediate"),
        ("No Equipment Challenge", 30, "challenge", "Beginner"),
        ("Ultimate Strength", 60, "challenge", "Advanced"),
        ("Daily Mobility", 21, "challenge", "Beginner"),
        ("HIIT Hero", 30, "challenge", "Advanced"),
        ("Mind & Body", 28, "challenge", "Beginner"),
        ("Power Builder", 45, "challenge", "Advanced"),
        ("Wellness Week", 7, "challenge", "Beginner"),
        ("Athlete Evolution", 90, "challenge", "Advanced"),
        ("Stress Relief Challenge", 14, "challenge", "Beginner"),
        ("Maximum Performance", 60, "challenge", "Advanced"),
        ("Posture Perfect", 30, "challenge", "Intermediate"),
        ("Home Warrior", 30, "challenge", "Beginner"),
        ("Elite Training Camp", 60, "challenge", "Advanced"),
        ("Gentle Movement", 21, "challenge", "Beginner"),
        ("CrossFit Challenge", 45, "challenge", "Advanced"),
        ("Balance & Grace", 28, "challenge", "Intermediate"),
        ("Quick Start", 14, "challenge", "Beginner"),
        ("Pro Level Push", 60, "challenge", "Advanced"),
        ("Yoga Flow Journey", 30, "challenge", "Intermediate"),
        ("Walk Every Day", 30, "challenge", "Beginner"),
        ("Muscle Mania", 45, "challenge", "Advanced"),
        ("Stretch & Strengthen", 21, "challenge", "Intermediate"),
        ("First Timer", 7, "challenge", "Beginner"),
        ("Bodyweight Beast", 60, "challenge", "Advanced"),
        ("Daily Dose", 30, "challenge", "Beginner"),
        ("Extreme Athlete", 90, "challenge", "Advanced"),
        ("Morning Glory", 21, "challenge", "Beginner"),
        ("Tactical Training", 45, "challenge", "Advanced"),
        ("Evening Calm", 14, "challenge", "Beginner"),
        ("Warrior Path", 60, "challenge", "Advanced"),
        ("Active Lifestyle", 30, "challenge", "Intermediate"),
        ("Starter Pack", 7, "challenge", "Beginner"),
        ("Beast Unleashed", 90, "challenge", "Advanced"),
        ("Mindful Movement", 21, "challenge", "Beginner"),
        ("Combat Ready", 60, "challenge", "Advanced"),
        ("Balance Builder", 28, "challenge", "Intermediate"),
        ("Baby Steps", 14, "challenge", "Beginner"),
        ("Iron Will", 60, "challenge", "Advanced"),
        ("Core Connection", 30, "challenge", "Intermediate"),
        ("Gentle Start", 7, "challenge", "Beginner"),
        ("Military Fitness", 90, "challenge", "Advanced"),
        ("Wellness Challenge", 30, "challenge", "Beginner"),
        ("Special Forces", 60, "challenge", "Advanced"),
        ("Flexibility Focus", 21, "challenge", "Intermediate"),
        ("New You Challenge", 30, "challenge", "Beginner"),
        ("Navy SEAL Test", 45, "challenge", "Advanced"),
        ("Daily Yoga", 30, "challenge", "Intermediate"),
        ("Couch to 5K", 42, "challenge", "Beginner"),
        ("Elite Performance", 90, "challenge", "Advanced"),
        ("Mobility Master", 28, "challenge", "Intermediate"),
        ("First Week Challenge", 7, "challenge", "Beginner"),
        ("Superhero Training", 60, "challenge", "Advanced"),
        ("Calm & Centered", 21, "challenge", "Beginner"),
        ("Pro Athlete Prep", 90, "challenge", "Advanced"),
        ("Steady Progress", 30, "challenge", "Intermediate"),
        ("Easy Does It", 14, "challenge", "Beginner"),
        ("Unstoppable Force", 60, "challenge", "Advanced"),
        ("Flexibility Plus", 30, "challenge", "Intermediate"),
        ("Beginner Basics", 7, "challenge", "Beginner"),
        ("Ultimate Warrior", 90, "challenge", "Advanced"),
        ("Balance Journey", 21, "challenge", "Intermediate"),
        ("Simple Start", 14, "challenge", "Beginner"),
        ("Extreme Limits", 60, "challenge", "Advanced"),
        ("Core & More", 30, "challenge", "Intermediate"),
        ("Gentle Introduction", 7, "challenge", "Beginner"),
        ("Championship Level", 90, "challenge", "Advanced"),
        ("Strength & Stretch", 28, "challenge", "Intermediate"),
        ("Week One Success", 7, "challenge", "Beginner"),
        ("Olympian Training", 60, "challenge", "Advanced"),
        ("Wellness Month", 30, "challenge", "Beginner"),
        ("Peak Performance", 90, "challenge", "Advanced"),
        ("Daily Dedication", 30, "challenge", "Intermediate"),
        ("Foundation Builder", 14, "challenge", "Beginner"),
        ("Maximum Effort", 60, "challenge", "Advanced"),
        ("Balanced Life", 30, "challenge", "Intermediate"),
        ("Fresh Start", 7, "challenge", "Beginner"),
        ("Legend Status", 90, "challenge", "Advanced")
    ]
}

